### ISSUE TITLE
Please rename

### ISSUE THREAD

**Issue by anibalsolon** [BrubHubPremium/general#1]
Rename repo to `General` or rename other repos to `analysis` and `plotting`

Thanks.

**Comment by amekhanik** [comment]
Can the person who created the org only access repo settings? Cause I can't change it

**Comment by anibalsolon** [comment]
![image](https://user-images.githubusercontent.com/562525/64266659-f4798680-cf02-11e9-9f5e-72b2f0f10c28.png)

**Comment by amekhanik** [comment]
**OOOOOOOFFFFF**
